### ISSUE TITLE
Crash in Jni method 

### ISSUE THREAD

**Issue by yangtianrui95** [Kuanlin-Chen/AESpeedTest#1]
Choiced mode in Jni method , it doesn't work.(Nexus6)
 
```
Dumping all threads without appropriate locks held: thread list lock mutator lock
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422] All threads:
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422] DALVIK THREADS (14):
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422] "main" prio=10 tid=1 Runnable
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   | group="" sCount=0 dsCount=0 obj=0x73c946b8 self=0xaaa85400
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   | sysTid=17956 nice=-10 cgrp=default sched=0/0 handle=0xad710534
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   | state=R schedstat=( 399846084 64839268 541 ) utm=31 stm=7 core=2 HZ=100
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   | stack=0xbe553000-0xbe555000 stackSize=8MB
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   | held mutexes= "abort lock" "mutator lock"(shared held)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #00 pc 00351069  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #01 pc 00331729  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+304)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #02 pc 0034382f  /system/lib/libart.so (_ZN3art14DumpCheckpoint3RunEPNS_6ThreadE+622)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #03 pc 0033d7bd  /system/lib/libart.so (_ZN3art10ThreadList13RunCheckpointEPNS_7ClosureE+336)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #04 pc 0033d4b7  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEb+586)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #05 pc 003245f5  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+372)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #06 pc 0031b351  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+92)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #07 pc 000b526b  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1134)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #08 pc 0023a609  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1584)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #09 pc 0023a85f  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+58)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #10 pc 000cac4b  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+42)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #11 pc 000ca219  /system/lib/libart.so (_ZN3art11ScopedCheck10CheckArrayERNS_18ScopedObjectAccessEP7_jarray+124)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #12 pc 000c987f  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+74)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #13 pc 000c8d21  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+800)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #14 pc 000c5285  /system/lib/libart.so (_ZN3art8CheckJNI14GetArrayLengthEP7_JNIEnvP7_jarray+444)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #15 pc 00002807  /data/app/chen.kuanlin.aespeedtest-1/lib/arm/libaes_jni.so (Java_chen_kuanlin_aespeedtest_JNI_crypt+34)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   native: #16 pc 00029493  /data/app/chen.kuanlin.aespeedtest-1/oat/arm/base.odex (Java_chen_kuanlin_aespeedtest_JNI_crypt___3BJI+126)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at chen.kuanlin.aespeedtest.JNI.crypt(Native method)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at chen.kuanlin.aespeedtest.JNI.Encrypt(JNI.java:35)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at chen.kuanlin.aespeedtest.Context.executeEncrypt(Context.java:12)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at chen.kuanlin.aespeedtest.MainActivity$2.onClick(MainActivity.java:115)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at android.view.View.performClick(View.java:5637)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at android.view.View$PerformClick.run(View.java:22429)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at android.os.Handler.handleCallback(Handler.java:751)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at android.os.Handler.dispatchMessage(Handler.java:95)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at android.os.Looper.loop(Looper.java:154)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at android.app.ActivityThread.main(ActivityThread.java:6119)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at java.lang.reflect.Method.invoke!(Native method)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-06 11:12:08.072 17956-17956/chen.kuanlin.aespeedtest A/art: art/runtime/runtime.cc:422]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by Kuanlin-Chen** [comment]
I'll check it as soon as possible.
What's your Android version?

**Comment by yangtianrui95** [comment]
Thx, this crash happen in  Android 7.11.

**Comment by Kuanlin-Chen** [comment]
Did you grant the "Storage" permission to the application ?

**Comment by yangtianrui95** [comment]
Carefully read the code, sdcard does not Luna.pdf file is caused by the reasons for the crash, encrypted file should be placed in the asset folder.

**Comment by Kuanlin-Chen** [comment]
What you mean is "sdcard does not have Luna.pdf file" in your device ?
In this project, encrypted file will be renamed as "cipher.pdf".
